<?php
//============================================================================//
// File: %filename%
//----------------------------------------------------------------------------
// LICENSE
//
//----------------------------------------------------------------------------
// Original Author of this file: ____________________
// Purpose of this file: ____________________
//----------------------------------------------------------------------------
//    Generated by: AksiIDE - KIOSS Project IDE for PHP
//    Generated on: %generate.date%
// Last Updated by:
// Last Updated on:
//----------------------------------------------------------------------------//

/**
 * SiteController is the default controller to handle user requests.
 */
class SiteController extends CController
{
	/**
	 * Index action is the default action in a controller.
	 */
	public function actionIndex()
	{
		echo 'Hello World';
	}
}
