<?php
/*============================================================================
 * File: User.php
 *---------------------------------------------------------------------------
 * LICENSE :
 *---------------------------------------------------------------------------
 * Original Author of this file: ____________________
 * Purpose of this file: ____________________
 *---------------------------------------------------------------------------
 * Generated by AksiIDE - KIOSS Project IDE for PHP
 * Generated date 2012/12/24 18:07:02
 * @package  BMT
 * @updateby
 * @updateon
 *---------------------------------------------------------------------------*/

 /*

 contoh penggunaan grid
 http://url/app/%module.id%/view/type/grid


 */

require_once DataUtil::formatForOS( "modules/%module.name%/config.app.php");
include_once DataUtil::formatForOS( 'modules/%module.name%/lib/%module.name%/vendor/lib.php');
include_once("system/Theme/lib/vendor/Mobile_Detect.php");


/**
 * This is the User controller class providing navigation and interaction functionality.
 */
class %module.name%_Controller_Grid extends Zikula_AbstractController {

	private $bExternalDB = false;
	private $sTableName = "bmt_anggota";
  private $sPrimaryKey = "No_Anggota";
	private $sOrderBy = "No_Anggota desc";
  // field yang akan ditampilkan
	private $aFieldDef = array(
			"No_Anggota" => array( "title" =>  "No Anggota", "link"=>true, "align"=>"center"),
			"Nama" => array( "title" =>  "Nama", "link"=>true),
			"Alamat" => array( "title" =>  "Alamat", "align"=>"left"),
			"No_Identitas" => array( "title" =>  "No ID"),
			"Tgl_Lahir" => array( "title" =>  "Lahir", "type"=>"date"),
			"Pekerjaan" => array( "title" =>  "Pekerjaan", "hidden"=>true),
			"Jns_Anggota" => array( "title" =>  "Jns Anggota"),
			"Sim_Pokok" => array( "title" =>  "S Pokok", "type"=>"number", "align"=>"right"),
			"Status" => array( "title" =>  "Status", "hidden"=>true),
			"Ket" => array( "title" =>  "Ket", "hidden"=>true),
			"Agama" => array( "title" =>  "Agama"),
			"Pendidikan" => array( "title" =>  "Pendidikan", "align"=>"center"),
			);
  // searcy by @ header grid, kanan atas
  private $aSearchBy = array(
  	"Nama" => "Nama",
    "No_Anggota" => "No Anggota",
  );
  // opsional, action2 url per record, %id akan di replace sesuai value field primary-key-nya
  private $aActionURL = array(
  	"edit" => array(
    	"type" => "ajax",
      "link" => "xxxxxx/%id"
    	),
  	"delete" => array(
    	"type" => "ajax",
      "link" => "del/%id"
    	),
  );


  /*
  function __construct($objectId){
  	parent::__construct($objectId);
  }
  */

  // bypass illegal parameter to 'main'
	function __call($method, $args){
		$lsMethod = __METHOD__;
		//$lsFungsi = __FUNCTION__;
    return $this->main( $args);
	}

	/**
	 * This method is the default function.
	 * Called whenever the module's area is called without defining arguments.
	 * @param array $args Array.
	 * @return string|boolean Output.
	 */
	public function main( $args){
  	return $this->view( $args);
	}


	public function wow( $args){
  	$now = DateUtil::getDatetime();
  	$lsHTML = "<pre>$now;\n".print_r( $_REQUEST, true);
  	return $lsHTML;
	}
	public function testecho( $args){
    if ( !MyAksi_Util::isInternalCall( )) {
    	$lsURL = System::getBaseURL() . MyAksi_Util::url($this->name, 'anggota', 'wow');
    	return MyAksi_Util::GoToURL( $lsURL);
    }

  	// error
    //echo %module.name%_Anggota_wow();
    //die;
  	$now = DateUtil::getDatetime();
  	$lsHTML = "<pre>;\n".print_r( $_REQUEST, true);
  	return $lsHTML;
	}
  //http://%module.name%/app/%module.id%/testobject/type/anggota
	public function testobject( $args){
  	$this->oDBConn = DBConnectionStack::init( "%module.id%");
  	$loAnggota = new %module.name%_DBObject_Anggota( null, "No_Anggota");

    //$data = $loAnggota->get( $where, $sort, $startnum, $pagesize);
		$data = $loAnggota->get( "00742");
    $liID = $loAnggota->getID();
    $lsS = $loAnggota->getIDField();
    DBConnectionStack::popConnectionForce( true);
    echo "$liID - $lsS<pre>asdads";print_r( $data);die;
	}

  public function view( $args){
    if ( !MyAksi_Util::isInternalCall( )) {
    	$lsURL = System::getBaseURL() . MyAksi_Util::url($this->name, 'anggota', 'view');
    	return MyAksi_Util::GoToURL( $lsURL);
    }
		if (!SecurityUtil::checkPermission( $this->name, '::', ACCESS_READ)) {
    	//$lsHTML = LogUtil::registerPermissionError( ModUtil::url( $this->name, 'user', 'main'));
      $lsHTML = __( "Akses tidak diperbolehkan");
      $lsHTML = MyAksi_Util::fetch( 1, $lsHTML, $lsHTML, "" );
      return $lsHTML;
		}

  	$laActionURL = $this->aActionURL;
    $laActionURL = array();
  	$laData = array (
    	"db.external" => true,
      "db.name" => %module.name%_Constant::DB_CONNECTION_NAME,
      "table.key" => $this->sPrimaryKey,
      "table.name" => $this->sTableName,
      "table.order" => "No_Anggota desc",
      "table.limit" => %module.name%_Constant::DATA_LIMIT,
      "field.search" => $this->aSearchBy,
      "field.def" => $this->aFieldDef,
      "action" => $laActionURL,
    );
	  $laGridResult = ModUtil::apiFunc('MyAksi', 'Grid', 'view', $laData 	);

    $lsGridHTML = $laGridResult[ "aData"];
    if ( $laGridResult[ "iErr"] > 0){
    	$lsGridHTML = __( "Akses gagal"); // self error message; error message kadang sudah disampaikan di ["aData"];
    }

    $this->view->assign( 'bAjax', MyAksi_Util::isAjax() );
		$this->view->assign( 'iErr', $laGridResult[ "iErr"]);
		$this->view->assign( 'sGridHTML', $lsGridHTML);
		$lsHTML = $this->view->fetch( "anggota/view.tpl");

    $lsHTML = MyAksi_Util::fetch( $laGridResult[ "iErr"], $lsHTML, "", "" );
    return $lsHTML;
  }



}
