<html>
<head>
	<body>
		Welcome to project "<?php echo $projectname; ?>"<br>
		module : <?php echo $modulename; ?><br>
		This project generated by <b><?php echo $generator; ?></b>
	</body>
</head>
</html>


