<?php
/*
Plugin Name: %module.name%
Plugin Script: %module.name%.php
Plugin URI: http://aksiide.com/ref/%module.name%
Description: Wordpress Simple Plugin Generated By AksiIDE
Version: 0.1
Author: Your name
Author URI: http://aksiide.com

=== RELEASE NOTES ===
%generated.date% - v1.0 - first version
*/

// uncomment next line if you need functions in external PHP script;
// include_once(dirname(__FILE__).'/some-library-in-same-folder.php');

// ------------------
// %module.name% parameters will be saved in the database
function %module.name%_add_options() {
// %module.name%_add_options: add options to DB for this plugin
 add_option('%module.name%_nb_widgets', '75');
// add_option('%module.name%_...','...');
 }
 %module.name%_add_options();

// ------------------
// %module.name%_showhtml will generate the (HTML) output
function %module.name%_showhtml($param1 = 0, $param2 = "test") {
 global $wpdb;
// get your parameter values from the database
 $%module.name%_nb_widgets = get_option('%module.name%_nb_widgets');
// generate $%module.name%_html based on ...
// (your code)
// to do a query in the WP database, use the following line;
// $query = $wpdb->get_results("SELECT .. FROM $wpdb->.. WHERE .. ORDER BY ..");
// foreach ($query as $item) {
// (e.g.) $itemdate = $item->post_date_gmt;
// }
// content will be added when function '%module.name%_showhtml()' is called
 return $%module.name%_html;
 }


